model:
  checkpoint_path: "/root/nguyen/research/NLP/Final/code/t5_simplification/checkpoint-26470"
  gpu_device: "7"
  name: "t5-small"

data:
  test_cache: "./cached_datasets/test"
  cache_dir: "./cached_datasets"
  root_dir: "../datasets/"
  train_file: "train.jsonl"
  val_file: "valid.jsonl" 
  test_file: "test.jsonl"
  cache_dir: "./cached_datasets"
  

generation:
  max_length: 128
  num_beams: 4
  length_penalty: 2.0
  early_stopping: true
  batch_size: 8

evaluation:
  metrics:
    bleu: true
    rouge: true
    bert_score: true
  bert_score:
    model: "microsoft/deberta-xlarge-mnli"
    batch_size: 32
  
logging:
  level: "INFO"
  save_predictions: true
  results_dir: "./evaluation_results"