data:
  root_dir: "../datasets/"
  train_file: "train.jsonl"
  val_file: "valid.jsonl" 
  test_file: "test.jsonl"
  cache_dir: "./cached_datasets"

model:
  name: "t5-base"
  save_dir: "./t5_simplification"
  max_input_length: 512
  max_target_length: 128

training:
  seed: 42
  gpu_devices: "2,4,5,7"
  learning_rate: 5e-5
  train_batch_size: 16
  eval_batch_size: 8
  gradient_accumulation_steps: 4
  num_epochs: 3
  weight_decay: 0.01
  save_total_limit: 2
  logging_steps: 500
  warmup_steps: 0
  fp16: true
  num_workers: 4
  
tokenizer:
  prefix: "simplify: "